#!/usr/bin/env bash

if [[ "$1" == "-g" ]]; then
  run="valgrind --leak-check=full --show-leak-kinds=all"
  opts=-g
  # Static linking shows memory leaks and/or errors in valgrind.
  # TODO Do they mean something, or should they be ignored?
  # opts="$opts -static"
elif [[ "$1" == "-O" ]]; then
  # opts="-static -O3 -flto"
  opts="-static -O3"
  # Fails:
  # opts="-O3 -flto"
  run=""
else
  run=""
fi

time_arg=$2

timerun() {
  if [[ "$time_arg" == "-t" ]]; then
    /usr/bin/time -v $@
  else
    time $@
  fi
}

mkdir -p bin || exit
# Use c++11 because it's nice but also old enough it has better support.
time c++ $opts -Wall -Werror -Wpedantic -std=c++11 \
  -o bin/rio src/main.cpp || exit
timerun $run ./bin/rio tests/test1.rio || exit
